# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: katodia//TODO PAge descriptions
email: info@katodia.com
logo: katodia logox32.gif
description: > # this means to ignore newlines until "baseurl:"
  Aplicaciones móviles para Android y videojuegos. Desarrollo 
  web y posicionamiento web SEO y SEM. Nos ubicamos en Ponferrada, León.
baseurl: "" # the subpath of your site, e.g. /blog
url: "katodia.gitlab.io" # the base hostname & protocol for your site
meta: 
  keywords: desarrollo, aplicaciones, web, android, videojuegos, wordpress, Ponferrada

# Google Analytics
google_analytics: UA-59457770-1

# Build settings
markdown: kramdown
theme: geekyll

web_assets: assets/web/
post_assets: assets/posts/
portfolio_assets: assets/portfolio/
author_assets: assets/authors/
project_assets: assets/projects/

extra_js:
  - assets/js/contact-form.js
  - assets/js/anchor-animation.js

social_links:
  - platform: twitter
    url: //twitter.com/
    icon: fa fa-twitter
    title: Check my Twitter profile
  - platform: github
    url: //github.com/
    icon: fa fa-github
    title: Check my Github repos
  - platform: gitlab
    url: //gitlab.com/
    icon: fa fa-gitlab
    title: Check my gitlab repos
  - platform: livecoding
    url: //livecoding.tv/
    icon: fa fa-code
    title: Watch my LiveCoding streamings
  - platform: linkedin
    url: //linkedin.com/in/
    icon: fa fa-linkedin
    title: Check my LinkedIn profile
  - platform: googleplus
    url: //plus.google.com/
    icon: fa fa-google-plus-square
    title:
  - platform: email
    url: "mailto:"
    icon: fa fa-envelope
    title: "Send me a mail"

footer:
  copyright: Copyright &copy; 2014-2016 katodia. Licensed under terms of <a rel="license" href="https://opensource.org/licenses/MIT">MIT</a>.
  featuring: Site made with <a href="//jekyllrb.com" target="_blank" >Jekyll</a> and proudly hosted by <a href="//gitlab.com" target="_blank" >Gitlab</a>
  socials:
    github: katodia
    twitter: katodians
    email: info@katodia.com
    googleplus: +Katodia-Desarrollo-Aplicaciones
