# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: katodia
email: info@katodia.com
logo: katodia logox32.gif
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "192.168.0.164:4000" # the base hostname & protocol for your site
twitter_username: katodians
github_username:  katodia

# Build settings
markdown: kramdown
theme: geekyll

web_assets: assets/web/
post_assets: assets/posts/
portfolio_assets: assets/portfolio/
author_assets: assets/authors/
project_assets: assets/projects/

social:
  - livecoding: https://livecoding.tv/
  - twitter: 

extra_js:
  - assets/js/contact-form.js
  - assets/js/anchor-animation.js

member_social:
  - platform: twitter
    url: https://twitter.com/
    icon: fa fa-twitter
    title: Check my Twitter profile
  - platform: github
    url: https://github.com/
    icon: fa fa-github
    title: Check my Github repos
  - platform: gitlab
    url: https://gitlab.com/
    icon: fa fa-gitlab
    title: Check my gitlab repos
  - platform: livecoding
    url: https://livecoding.tv/
    icon: fa fa-code
    title: Watch my LiveCoding streamings
  - platform: linkedin
    url: https://linkedin.com/in/
    icon: fa fa-linkedin
    title: Check my LinkedIn profile
  - platform: email
    url: "mailto:"
    icon: fa fa-envelope
    title: "Send me a mail"